rest-wrapper:
  retryAttempts: 4
  delayBeforeRetry: 5
  retryMultiplier: 2
  minimumNumberOfCalls: 5
  failureRateThreshold: 25
  slowCallRateThreshold: 25
  slowCallDurationThreshold: 2
  permittedNumberOfCallsInHalfOpenState: 2
  maxWaitDurationInHalfOpenState: 10
  waitDurationInOpenState: 60
  slidingWindowType: COUNT_BASED
  slidingWindowSize: 5
  writableStackTraceEnabled: true
  automaticTransitionFromOpenToHalfOpenEnabled: true
  logEvents: true

spring:
  main:
    banner-mode=off: "off"

logging:
  level:
    org:
      apache: OFF
      springframework: OFF
